---
title: "Chirag's Paper"
date: "Updated on : `r date()`"
output: html_document
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## 1. Load libs

```{r setup,warning=FALSE,message=FALSE}
library(EnWAS)
library(splines)
library(ggplot2)
library(ggpubr)
library(dplyr)
```


## 2. Data

```{r data,warning=FALSE,message=FALSE}
library(DBI)
nhanes_db <- DBI::dbConnect(RSQLite::SQLite(), "C:\\projects\\data_nhanes\\nhanes_new.sqlite")



data <- dbGetQuery(nhanes_db, "SELECT demo.SEQN,
                                    (BPXDI1+BPXDI2)/2 AS DIASTOLIC,
                                    RIAGENDR,RIDAGEYR,RIDRETH1,BMXBMI, 
                                    INDFMPIR,LBXBCO,LBDBCOSI
                                  FROM
                                    DemographicVariablesAndSampleWeights as demo
                                  INNER JOIN BodyMeasures
                                  ON demo.SEQN=BodyMeasures.SEQN
                                  INNER JOIN BloodPressure ON
                                  demo.SEQN=BloodPressure.SEQN
                                  INNER JOIN ChromiumAndCobalt ON
                                  demo.SEQN=ChromiumAndCobalt.SEQN
                                  WHERE
                                      RIDAGEYR>40
                                    AND BMXBMI is not NULL
                                    AND BPXDI1 IS NOT NULL and BPXDI1 <> 0
                                    AND BPXDI2 IS NOT NULL and BPXDI2 <> 0
                                    AND LBDBCOSI IS NOT NULL
                                    AND LBXBCO IS NOT NULL
                       ")

years <- dbGetQuery(nhanes_db, "SELECT SEQN, years from demo")
data <- merge(data,years, by="SEQN")
data$years <- as.factor(data$years)
data$RIAGENDR <- as.factor(data$RIAGENDR)


dim(data)
sapply(data,function(x) sum(is.na(x)))

levels(data$years)


```
